/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.coffee_pos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 66982
 */
public class coffeebill extends javax.swing.JFrame {

    /**
     * Creates new form coffeebill
     */
    public coffeebill() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_payment = new javax.swing.JButton();
        bt_clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showmenu1 = new javax.swing.JTextArea();
        showprice1 = new javax.swing.JLabel();
        bill = new javax.swing.JScrollPane();
        Bill = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        showmenu2 = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_payment.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bt_payment.setText("Payment");
        bt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_paymentActionPerformed(evt);
            }
        });
        getContentPane().add(bt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 410, 93, 41));

        bt_clear.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 410, 93, 41));

        jLabel10.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 370, -1, -1));

        showmenu1.setColumns(20);
        showmenu1.setRows(5);
        jScrollPane1.setViewportView(showmenu1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 26, 245, 329));
        getContentPane().add(showprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 370, 62, 29));

        Bill.setColumns(20);
        Bill.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        Bill.setRows(5);
        bill.setViewportView(Bill);

        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 26, 381, 329));

        showmenu2.setColumns(20);
        showmenu2.setRows(5);
        jScrollPane2.setViewportView(showmenu2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 387, 245, 53));

        Back.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        Back.setText("Back to manu");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 410, -1, 41));

        jLabel11.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_paymentActionPerformed
        String path1 = "C:\\Users\\66982\\Documents\\GitHub\\oop-group-assignment-the-gang\\BillID.txt";
        BufferedReader br;
        String line;
        int n1=0;
        try {
            br = new BufferedReader(new FileReader(path1));
            while ((line = br.readLine()) != null) {
                String[] userdata = line.split(",");
                    n1 = Integer.valueOf(userdata[userdata.length-1]);
            }

        } catch (Exception e) {
        }
        
        String path2 = "C:\\Users\\66982\\Documents\\GitHub\\oop-group-assignment-the-gang\\bill"+n1+".txt";
        //String name = path.getName;
        
        File file1 = new File(path2);
        FileWriter writer;
        try {
            writer = new FileWriter(file1, true);
            writer.write(Bill.getText());
            writer.close();
        } catch (IOException e) {
            //e.printStackTrace();
        }
    }//GEN-LAST:event_bt_paymentActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        showmenu1.setText("");
        
        
    }//GEN-LAST:event_bt_clearActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Menucoffee Menucoffee = new Menucoffee();
        Menucoffee.show();
       
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coffeebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coffeebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coffeebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coffeebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coffeebill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    public javax.swing.JTextArea Bill;
    private javax.swing.JScrollPane bill;
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_payment;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea showmenu1;
    public javax.swing.JTextArea showmenu2;
    public javax.swing.JLabel showprice1;
    // End of variables declaration//GEN-END:variables
}
