/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.coffee_pos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author 66982
 */
public class Menucoffee extends javax.swing.JFrame {
    int sum_price =0;
    String sum_menu="";
    /**
     * Creates new form Menucoffee
     */
    public Menucoffee() {
        initComponents();
        showDate();
        showTime();
    }
    void showDate() {
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        Date.setText(s.format(date));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss:a");
                Time.setText(s.format(date));

            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bt_lattehot = new javax.swing.JButton();
        bt_lattecool = new javax.swing.JButton();
        bt_lattefrappe = new javax.swing.JButton();
        bt_ovaltinhot = new javax.swing.JButton();
        bt_ovaltincool = new javax.swing.JButton();
        bt_ovaltinfrappe = new javax.swing.JButton();
        bt_americanocool = new javax.swing.JButton();
        bt_americanohot = new javax.swing.JButton();
        bt_esspressocool = new javax.swing.JButton();
        bt_esspressohot = new javax.swing.JButton();
        bt_esspressofrappe = new javax.swing.JButton();
        bt_cappucinocool = new javax.swing.JButton();
        bt_cappucinohot = new javax.swing.JButton();
        bt_cappucinofrappe = new javax.swing.JButton();
        bt_payment = new javax.swing.JButton();
        bt_clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        showprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_showmenu = new javax.swing.JTextArea();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 68, 34));

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel2.setText("Latte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, -1, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel3.setText("Americano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 215, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel4.setText("Esspresso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 268, -1, -1));

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel5.setText("Cappucino");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 321, -1, -1));

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel6.setText("Ovaltine");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 162, -1, -1));

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel7.setText("HOT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 62, -1, -1));

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel8.setText("COOL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 62, -1, -1));

        jLabel9.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        bt_lattehot.setText("30");
        bt_lattehot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lattehotActionPerformed(evt);
            }
        });
        getContentPane().add(bt_lattehot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 113, 48, 31));

        bt_lattecool.setText("40");
        bt_lattecool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lattecoolActionPerformed(evt);
            }
        });
        getContentPane().add(bt_lattecool, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 113, 48, 31));

        bt_lattefrappe.setText("50");
        bt_lattefrappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lattefrappeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_lattefrappe, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 113, 48, 31));

        bt_ovaltinhot.setText("25");
        bt_ovaltinhot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ovaltinhotActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ovaltinhot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 166, 48, 31));

        bt_ovaltincool.setText("35");
        bt_ovaltincool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ovaltincoolActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ovaltincool, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 166, 48, 31));

        bt_ovaltinfrappe.setText("45");
        bt_ovaltinfrappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ovaltinfrappeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ovaltinfrappe, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 166, 48, 31));

        bt_americanocool.setText("40");
        bt_americanocool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_americanocoolActionPerformed(evt);
            }
        });
        getContentPane().add(bt_americanocool, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 219, 48, 31));

        bt_americanohot.setText("30");
        bt_americanohot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_americanohotActionPerformed(evt);
            }
        });
        getContentPane().add(bt_americanohot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 219, 48, 31));

        bt_esspressocool.setText("40");
        bt_esspressocool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_esspressocoolActionPerformed(evt);
            }
        });
        getContentPane().add(bt_esspressocool, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 272, 48, 31));

        bt_esspressohot.setText("30");
        bt_esspressohot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_esspressohotActionPerformed(evt);
            }
        });
        getContentPane().add(bt_esspressohot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 272, 48, 31));

        bt_esspressofrappe.setText("50");
        bt_esspressofrappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_esspressofrappeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_esspressofrappe, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 272, 48, 31));

        bt_cappucinocool.setText("40");
        bt_cappucinocool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cappucinocoolActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cappucinocool, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 321, 48, 31));

        bt_cappucinohot.setText("30");
        bt_cappucinohot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cappucinohotActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cappucinohot, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 321, 48, 31));

        bt_cappucinofrappe.setText("50");
        bt_cappucinofrappe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cappucinofrappeActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cappucinofrappe, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 321, 48, 31));

        bt_payment.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bt_payment.setText("Payment");
        bt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_paymentActionPerformed(evt);
            }
        });
        getContentPane().add(bt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 421, 93, 41));

        bt_clear.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 421, 93, 41));

        jLabel10.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 378, -1, -1));

        showprice.setText("0");
        getContentPane().add(showprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 385, 75, 25));

        tf_showmenu.setColumns(20);
        tf_showmenu.setRows(5);
        jScrollPane1.setViewportView(tf_showmenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 39, 251, 333));

        Date.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 11, 136, 45));

        Time.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 11, 136, 45));

        jLabel12.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel12.setText("FRAPPE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 62, -1, -1));

        jLabel13.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jLabel13.setText("FRAPPE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 62, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_lattehotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lattehotActionPerformed
        sum_menu+= "Hot Latte\t"+Integer.valueOf(bt_lattehot.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_lattehot.getText());
        showprice.setText(String.valueOf(sum_price)); 
    }//GEN-LAST:event_bt_lattehotActionPerformed

    private void bt_lattecoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lattecoolActionPerformed
        sum_menu+= "Cool Latte\t"+Integer.valueOf(bt_lattecool.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_lattecool.getText());
        showprice.setText(String.valueOf(sum_price)); 
    }//GEN-LAST:event_bt_lattecoolActionPerformed

    private void bt_lattefrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lattefrappeActionPerformed
        sum_menu+= "Frappe Latte\t"+Integer.valueOf(bt_lattefrappe.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_lattefrappe.getText());
        showprice.setText(String.valueOf(sum_price)); 
    }//GEN-LAST:event_bt_lattefrappeActionPerformed

    private void bt_ovaltinhotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ovaltinhotActionPerformed
        sum_menu+= "Hot Ovaltin\t"+Integer.valueOf(bt_ovaltinhot.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_ovaltinhot.getText());
        showprice.setText(String.valueOf(sum_price)); 
    }//GEN-LAST:event_bt_ovaltinhotActionPerformed

    private void bt_ovaltincoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ovaltincoolActionPerformed
        sum_menu+= "Cool Ovaltin\t"+Integer.valueOf(bt_ovaltincool.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_ovaltincool.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_ovaltincoolActionPerformed

    private void bt_ovaltinfrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ovaltinfrappeActionPerformed
        sum_menu+= "Frappe Ovaltin\t"+Integer.valueOf(bt_ovaltinfrappe.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_ovaltinfrappe.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_ovaltinfrappeActionPerformed

    private void bt_americanohotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_americanohotActionPerformed
        sum_menu+= "Hot Americano\t"+Integer.valueOf(bt_americanohot.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_americanohot.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_americanohotActionPerformed

    private void bt_americanocoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_americanocoolActionPerformed
        sum_menu+= "Cool Americano\t"+Integer.valueOf(bt_americanocool.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_americanocool.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_americanocoolActionPerformed

    private void bt_esspressohotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_esspressohotActionPerformed
        sum_menu+= "Hot Esspresso\t"+Integer.valueOf(bt_esspressohot.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_esspressohot.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_esspressohotActionPerformed

    private void bt_esspressocoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_esspressocoolActionPerformed
        sum_menu+= "Cool Esspresso\t"+Integer.valueOf(bt_esspressocool.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_esspressocool.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_esspressocoolActionPerformed

    private void bt_esspressofrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_esspressofrappeActionPerformed
        sum_menu+= "Frappe Esspresso\t"+Integer.valueOf(bt_esspressofrappe.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_esspressofrappe.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_esspressofrappeActionPerformed

    private void bt_cappucinohotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cappucinohotActionPerformed
        sum_menu+= "Hot Cappucino\t"+Integer.valueOf(bt_cappucinohot.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_cappucinohot.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_cappucinohotActionPerformed

    private void bt_cappucinocoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cappucinocoolActionPerformed
        sum_menu+= "Cool Cappucino\t"+Integer.valueOf(bt_cappucinocool.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_cappucinocool.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_cappucinocoolActionPerformed

    private void bt_cappucinofrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cappucinofrappeActionPerformed
        sum_menu+= "Frappe Cappucino\t"+Integer.valueOf(bt_cappucinofrappe.getText())+"\tBath\n\r";
        tf_showmenu.setText(sum_menu);
        sum_price += Integer.valueOf(bt_cappucinofrappe.getText());
        showprice.setText(String.valueOf(sum_price));
    }//GEN-LAST:event_bt_cappucinofrappeActionPerformed

    private void bt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_paymentActionPerformed
        // TODO add your handling code here:
        String path1 = "C:\\Users\\66982\\Documents\\GitHub\\oop-group-assignment-the-gang\\BillID.txt";
        BufferedReader br;
        String line;
        int n1=0;
        try {
            br = new BufferedReader(new FileReader(path1));
            while ((line = br.readLine()) != null) {
                String[] userdata = line.split(",");
                    n1 = Integer.valueOf(userdata[userdata.length-1])+1;
            }

        } catch (Exception e) {
        }
        String path2 = "C:\\Users\\66982\\Documents\\GitHub\\oop-group-assignment-the-gang\\BillID.txt";
        //String name = path.getName;
        
        File file = new File(path2);
        FileWriter writer;
        try {
            writer = new FileWriter(file, true);
            writer.write(n1+",");
            writer.close();
        } catch (IOException e) {
            //e.printStackTrace();
        }
        coffeebill coffeebill = new coffeebill();
        coffeebill.showmenu1.setText(sum_menu);
        coffeebill.showprice1.setText(String.valueOf(sum_price));
        coffeebill.Bill.setText("Bill num : "+n1 + "\r\nPNFO Cafe\r\nTime: "+Time.getText()+"\r\nDate: "+Date.getText()+"\r\n"+sum_menu+"\r\n Price "+sum_price+" Bath");
        
        coffeebill.show();
        
    }//GEN-LAST:event_bt_paymentActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        tf_showmenu.setText("");
        showprice.setText("");
        
    }//GEN-LAST:event_bt_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menucoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menucoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menucoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menucoffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menucoffee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Date;
    public javax.swing.JLabel Time;
    private javax.swing.JButton bt_americanocool;
    private javax.swing.JButton bt_americanohot;
    private javax.swing.JButton bt_cappucinocool;
    private javax.swing.JButton bt_cappucinofrappe;
    private javax.swing.JButton bt_cappucinohot;
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_esspressocool;
    private javax.swing.JButton bt_esspressofrappe;
    private javax.swing.JButton bt_esspressohot;
    private javax.swing.JButton bt_lattecool;
    private javax.swing.JButton bt_lattefrappe;
    private javax.swing.JButton bt_lattehot;
    private javax.swing.JButton bt_ovaltincool;
    private javax.swing.JButton bt_ovaltinfrappe;
    private javax.swing.JButton bt_ovaltinhot;
    private javax.swing.JButton bt_payment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField showprice;
    public javax.swing.JTextArea tf_showmenu;
    // End of variables declaration//GEN-END:variables
}
